# Generated by Django 3.1.2 on 2020-11-15 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='dni',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='image',
            field=models.ImageField(default='empty.png', upload_to=''),
        ),
    ]
